"use client";
import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getTelegramInitData} from "../../../../lib/telegram-init-data";

type WindowType="24h"|"7d"|"30d";
type LearningData={generatedAt:string;training:{count:number;required:number;remaining:number};scores:{v2:number;v3:number;candidate:number};evaluation:{candidate:{eligible:boolean;sampleSize:number};split:{train:number;test:number;quality:number;risk:number};gates:Record<string,boolean>;verdict:string};latest:Array<{snapshot_at:string;active_score:number;shadow_score:number;candidate_score:number;candidate_version:number;status:string;created_at:string}>;policy:{productionRanking:string;candidate:string;automaticPromotion:boolean}};
type Eval={sampleSize:number;active:{qualityUplift:number;topRiskRate:number};shadow:{qualityUplift:number;topRiskRate:number};verdict:string};
type HistoryRow={window_type:WindowType;evaluated_at:string;paired_count:number;verdict:string;evaluation:Eval};
type ShadowData={windows:Record<WindowType,Eval>;history:Record<WindowType,HistoryRow[]>};
type CanaryData={state:{status:"ACTIVE"|"KILLED";reason:string|null};evaluation:{verdict:string;reason:string|null;operational:{lastHour:number;fallbacks:number;fallbackRate:number};outcomes:{candidateN:number;controlN:number;candidateQualityRate:number;controlQualityRate:number;candidateRiskRate:number;controlRiskRate:number}};last24h:{total:number;CONTROL:number;CANDIDATE:number;FALLBACK_V2:number}};
const card:React.CSSProperties={border:"1px solid rgba(255,255,255,.09)",borderRadius:20,padding:18,background:"rgba(22,22,28,.94)"};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12};
const muted:React.CSSProperties={color:"#969baa",fontSize:13,lineHeight:1.5};
const pct=(v:number)=>`${(v*100).toFixed(1)}%`;
export default function ShadowPage(){
 const router=useRouter();const [data,setData]=useState<LearningData|null>(null);const [shadow,setShadow]=useState<ShadowData|null>(null);const [canary,setCanary]=useState<CanaryData|null>(null);const [state,setState]=useState("loading");
 const load=useCallback(async()=>{setState("loading");const initData=await getTelegramInitData();if(!initData){setState("denied");return;}const headers={"Content-Type":"application/json"};const body=JSON.stringify({initData});const [lr,sr,cr]=await Promise.all([fetch("/api/admin/aura/learning-shadow",{method:"POST",headers,body}),fetch("/api/admin/aura/shadow-evaluation",{method:"POST",headers,body}),fetch("/api/admin/aura/canary-health",{method:"POST",headers,body})]);if(lr.status===404||sr.status===404||cr.status===404){setState("denied");return;}const [lb,sb,cb]=await Promise.all([lr.json().catch(()=>null),sr.json().catch(()=>null),cr.json().catch(()=>null)]);if(!lr.ok||!lb?.ok||!sr.ok||!sb?.ok||!cr.ok||!cb?.ok){setState("error");return;}setData(lb);setShadow(sb);setCanary(cb);setState("ready");},[]);
 useEffect(()=>{load();},[load]);
 const historyRows=shadow?(["24h","7d","30d"] as const).flatMap(w=>shadow.history?.[w]??[]).sort((a,b)=>b.evaluated_at.localeCompare(a.evaluated_at)):[];
 if(state==="denied")return <main style={{minHeight:"100dvh",display:"grid",placeItems:"center",background:"#09090c",color:"#fff"}}>Page not found.</main>;
 return <main style={{minHeight:"100dvh",background:"#09090c",color:"#f7f7fb",padding:"calc(18px + env(safe-area-inset-top)) 14px 40px"}}><div style={{maxWidth:1100,margin:"0 auto"}}>
 <header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:1.5,color:"#8a95ff"}}>AURA INTERNAL · LEARNING</div><h1 style={{margin:"5px 0",fontSize:"clamp(30px,8vw,48px)"}}>Shadow Lab</h1><p style={muted}>V2 → V3 → Learning Candidate. Production ranking остаётся V2.</p></div><div style={{display:"flex",gap:8}}><button onClick={()=>router.push("/admin/aura")} style={{padding:"10px 13px",borderRadius:12,border:"1px solid #333",background:"#17171d",color:"#fff",fontWeight:800}}>← AURA Match</button><button onClick={load} style={{padding:"10px 13px",borderRadius:12,border:0,background:"#fff",color:"#09090c",fontWeight:900}}>↻</button></div></header>
 {state==="loading"&&!data?<div style={{padding:80,textAlign:"center",color:"#888"}}>Загрузка…</div>:state==="error"?<div style={{...card,marginTop:30}}>Не удалось загрузить Shadow Lab.</div>:data&&shadow&&canary&&<>
 <section style={{...grid,marginTop:28}}><article style={card}><div style={muted}>Production</div><div style={{fontSize:32,fontWeight:900}}>V{data.policy.productionRanking}</div></article><article style={card}><div style={muted}>Training · 24h</div><div style={{fontSize:32,fontWeight:900}}>{data.training.count} / {data.training.required}</div><p style={muted}>Осталось: {data.training.remaining}</p></article><article style={card}><div style={muted}>Candidate</div><div style={{fontSize:25,fontWeight:900}}>{data.evaluation.verdict}</div><p style={muted}>SHADOW_ONLY · auto promotion OFF</p></article><article style={card}><div style={muted}>Candidate snapshots</div><div style={{fontSize:32,fontWeight:900}}>{data.scores.candidate}</div></article></section>
 <h2 style={{margin:"30px 0 12px"}}>Canary Health</h2><section style={grid}><article style={card}><div style={muted}>Kill switch</div><div style={{fontSize:28,fontWeight:900}}>{canary.state.status}</div><p style={muted}>{canary.state.reason??"Причин для остановки нет"}</p></article><article style={card}><div style={muted}>Safety verdict</div><div style={{fontSize:28,fontWeight:900}}>{canary.evaluation.verdict}</div><p style={muted}>Fallback 1h: {pct(canary.evaluation.operational.fallbackRate)} ({canary.evaluation.operational.fallbacks}/{canary.evaluation.operational.lastHour})</p></article><article style={card}><div style={muted}>Traffic · 24h</div><div style={{fontSize:28,fontWeight:900}}>{canary.last24h.total}</div><p style={muted}>Candidate {canary.last24h.CANDIDATE} · Control {canary.last24h.CONTROL} · Fallback {canary.last24h.FALLBACK_V2}</p></article><article style={card}><div style={muted}>Quality · Candidate / Control</div><div style={{fontSize:24,fontWeight:900}}>{pct(canary.evaluation.outcomes.candidateQualityRate)} / {pct(canary.evaluation.outcomes.controlQualityRate)}</div><p style={muted}>Risk {pct(canary.evaluation.outcomes.candidateRiskRate)} / {pct(canary.evaluation.outcomes.controlRiskRate)} · n={canary.evaluation.outcomes.candidateN}/{canary.evaluation.outcomes.controlN}</p></article></section>
 <h2 style={{margin:"30px 0 12px"}}>V2 ↔ V3 · текущие окна</h2><section style={grid}>{(["24h","7d","30d"] as const).map(w=>{const e=shadow.windows[w];return <article key={w} style={card}><div style={{display:"flex",justifyContent:"space-between",gap:8}}><strong>{w}</strong><span style={muted}>{e.verdict}</span></div><div style={{fontSize:30,fontWeight:900,marginTop:10}}>n={e.sampleSize}</div><p style={muted}>Quality uplift: V2 {pct(e.active.qualityUplift)} · V3 {pct(e.shadow.qualityUplift)}</p><p style={muted}>Top risk: V2 {pct(e.active.topRiskRate)} · V3 {pct(e.shadow.topRiskRate)}</p></article>})}</section>
 <h2 style={{margin:"30px 0 12px"}}>История evaluation</h2><section style={card}>{historyRows.length===0?<p style={muted}>История начнёт накапливаться после scheduled evaluation.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:760,borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Time","Window","n","Verdict","V2 uplift","V3 uplift","V2 risk","V3 risk"].map(x=><th key={x} style={{padding:9,textAlign:"right",borderBottom:"1px solid #333",color:"#999"}}>{x}</th>)}</tr></thead><tbody>{historyRows.map((x,i)=><tr key={`${x.evaluated_at}-${x.window_type}-${i}`}>{[new Date(x.evaluated_at).toLocaleString("ru-RU"),x.window_type,x.paired_count,x.verdict,pct(x.evaluation.active.qualityUplift),pct(x.evaluation.shadow.qualityUplift),pct(x.evaluation.active.topRiskRate),pct(x.evaluation.shadow.topRiskRate)].map((v,j)=><td key={j} style={{padding:9,textAlign:"right",borderBottom:"1px solid #222",fontWeight:j>=2?800:500}}>{v}</td>)}</tr>)}</tbody></table></div>}</section>
 <h2 style={{margin:"30px 0 12px"}}>Offline Candidate gates</h2><section style={grid}>{Object.entries(data.evaluation.gates).map(([k,v])=><article key={k} style={card}><div style={muted}>{k}</div><div style={{fontSize:24,fontWeight:900,marginTop:6}}>{v?"PASS":"HOLD"}</div></article>)}</section>
 <h2 style={{margin:"30px 0 12px"}}>Последние Candidate snapshots</h2><section style={card}>{data.latest.length===0?<p style={muted}>Пока нет: Candidate начнёт записываться после прохождения offline gates.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:650,borderCollapse:"collapse",fontSize:12}}><tbody>{data.latest.map((x,i)=><tr key={i}>{[new Date(x.snapshot_at).toLocaleString("ru-RU"),x.active_score,x.shadow_score,x.candidate_score,x.candidate_version,x.status].map((v,j)=><td key={j} style={{padding:9,textAlign:"right",borderBottom:"1px solid #222"}}>{v}</td>)}</tr>)}</tbody></table></div>}</section>
 </>}
 </div></main>;
}
