"use client";
import {useCallback,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {getTelegramInitData} from "../../../../lib/telegram-init-data";

type Data={generatedAt:string;training:{count:number;required:number;remaining:number};scores:{v2:number;v3:number;candidate:number};evaluation:{candidate:{eligible:boolean;sampleSize:number;weights:Record<string,number>;diagnostics:Record<string,number>};split:{train:number;test:number;quality:number;risk:number};metrics:Record<string,number>;gates:Record<string,boolean>;verdict:string};latest:Array<{snapshot_at:string;active_score:number;shadow_score:number;candidate_score:number;candidate_version:number;status:string;created_at:string}>;policy:{productionRanking:string;candidate:string;automaticPromotion:boolean}};
const card:React.CSSProperties={border:"1px solid rgba(255,255,255,.09)",borderRadius:20,padding:18,background:"rgba(22,22,28,.94)"};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12};
const muted:React.CSSProperties={color:"#969baa",fontSize:13,lineHeight:1.5};
export default function ShadowPage(){
 const router=useRouter();const [data,setData]=useState<Data|null>(null);const [state,setState]=useState("loading");
 const load=useCallback(async()=>{setState("loading");const initData=await getTelegramInitData();if(!initData){setState("denied");return;}const r=await fetch("/api/admin/aura/learning-shadow",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData})});if(r.status===404){setState("denied");return;}const b=await r.json().catch(()=>null);if(!r.ok||!b?.ok){setState("error");return;}setData(b);setState("ready");},[]);
 useEffect(()=>{load();},[load]);
 if(state==="denied")return <main style={{minHeight:"100dvh",display:"grid",placeItems:"center",background:"#09090c",color:"#fff"}}>Page not found.</main>;
 return <main style={{minHeight:"100dvh",background:"#09090c",color:"#f7f7fb",padding:"calc(18px + env(safe-area-inset-top)) 14px 40px"}}><div style={{maxWidth:1100,margin:"0 auto"}}>
  <header style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",flexWrap:"wrap"}}><div><div style={{fontSize:11,fontWeight:900,letterSpacing:1.5,color:"#8a95ff"}}>AURA INTERNAL · LEARNING</div><h1 style={{margin:"5px 0",fontSize:"clamp(30px,8vw,48px)"}}>Shadow Lab</h1><p style={muted}>V2 → V3 → Learning Candidate. Candidate не влияет на production ranking.</p></div><div style={{display:"flex",gap:8}}><button onClick={()=>router.push("/admin/aura")} style={{padding:"10px 13px",borderRadius:12,border:"1px solid #333",background:"#17171d",color:"#fff",fontWeight:800}}>← AURA Match</button><button onClick={load} style={{padding:"10px 13px",borderRadius:12,border:0,background:"#fff",color:"#09090c",fontWeight:900}}>↻</button></div></header>
  {state==="loading"&&!data?<div style={{padding:80,textAlign:"center",color:"#888"}}>Загрузка…</div>:state==="error"?<div style={{...card,marginTop:30}}>Не удалось загрузить Learning Shadow.</div>:data&&<>
   <section style={{...grid,marginTop:28}}><article style={card}><div style={muted}>Production</div><div style={{fontSize:32,fontWeight:900}}>V{data.policy.productionRanking}</div><p style={muted}>Пользовательская выдача.</p></article><article style={card}><div style={muted}>Training examples · 24h</div><div style={{fontSize:32,fontWeight:900}}>{data.training.count} / {data.training.required}</div><p style={muted}>До базового eligibility: {data.training.remaining}</p></article><article style={card}><div style={muted}>Candidate verdict</div><div style={{fontSize:25,fontWeight:900}}>{data.evaluation.verdict}</div><p style={muted}>Eligible: {data.evaluation.candidate.eligible?"да":"нет"}</p></article><article style={card}><div style={muted}>Candidate snapshots</div><div style={{fontSize:32,fontWeight:900}}>{data.scores.candidate}</div><p style={muted}>Только SHADOW_ONLY.</p></article></section>
   <h2 style={{margin:"30px 0 12px"}}>Слои score</h2><section style={grid}><article style={card}><div style={muted}>V2 active</div><div style={{fontSize:30,fontWeight:900}}>{data.scores.v2}</div></article><article style={card}><div style={muted}>V3 shadow</div><div style={{fontSize:30,fontWeight:900}}>{data.scores.v3}</div></article><article style={card}><div style={muted}>Candidate shadow</div><div style={{fontSize:30,fontWeight:900}}>{data.scores.candidate}</div></article></section>
   <h2 style={{margin:"30px 0 12px"}}>Offline gates</h2><section style={grid}>{Object.entries(data.evaluation.gates).map(([k,v])=><article key={k} style={card}><div style={muted}>{k}</div><div style={{fontSize:24,fontWeight:900,marginTop:6}}>{v?"PASS":"HOLD"}</div></article>)}</section>
   <h2 style={{margin:"30px 0 12px"}}>Train / holdout</h2><section style={grid}>{Object.entries(data.evaluation.split).map(([k,v])=><article key={k} style={card}><div style={muted}>{k}</div><div style={{fontSize:27,fontWeight:900}}>{v}</div></article>)}</section>
   <h2 style={{margin:"30px 0 12px"}}>Последние Candidate snapshots</h2><section style={card}>{data.latest.length===0?<p style={muted}>Пока нет: Candidate начнёт записываться после прохождения offline gates.</p>:<div style={{overflowX:"auto"}}><table style={{width:"100%",minWidth:650,borderCollapse:"collapse",fontSize:12}}><thead><tr>{["Time","V2","V3","Candidate","Version","Status"].map(x=><th key={x} style={{padding:9,textAlign:"right",borderBottom:"1px solid #333",color:"#999"}}>{x}</th>)}</tr></thead><tbody>{data.latest.map((x,i)=><tr key={i}>{[new Date(x.snapshot_at).toLocaleString("ru-RU"),x.active_score,x.shadow_score,x.candidate_score,x.candidate_version,x.status].map((v,j)=><td key={j} style={{padding:9,textAlign:"right",borderBottom:"1px solid #222",fontWeight:j>0?800:500}}>{v}</td>)}</tr>)}</tbody></table></div>}</section>
  </>}
 </div></main>;
}
