import {NextResponse} from "next/server";
import {authorizeAuraAdmin} from "../../../../../lib/server/admin/aura";
import {buildPairFeatures,buildUserFeatures,persistPairFeatureSnapshot,persistUserFeatureSnapshot} from "../../../../../lib/server/match/features";
import {buildConversationReadSignalsV1} from "../../../../../lib/server/match/features/read-signals";
import {persistPairFeatureSnapshotV2,persistUserFeatureSnapshotV2} from "../../../../../lib/server/match/features/snapshot-v2";
import type {AuraPairFeaturesV2,FeatureSnapshotV2} from "../../../../../lib/server/match/features/types-v2";
import {scoreAuraMatchV2} from "../../../../../lib/server/match/score/score-v2";
import {scoreAuraMatchV3} from "../../../../../lib/server/match/score/score-v3";
import {persistAuraScore} from "../../../../../lib/server/match/score/persistence";
import {supabaseAdmin} from "../../../../../lib/supabase-admin";

export const runtime="nodejs";export const dynamic="force-dynamic";
export async function POST(request:Request){let stage="request";try{
 const body=await request.json().catch(()=>null);stage="authorize";const authorization=authorizeAuraAdmin(body?.initData);if(!authorization.ok)return NextResponse.json({ok:false,error:"NOT_FOUND"},{status:404});
 const viewerUserId=typeof body?.viewerUserId==="string"?body.viewerUserId:"",candidateUserId=typeof body?.candidateUserId==="string"?body.candidateUserId:"";if(!viewerUserId||!candidateUserId||viewerUserId===candidateUserId)return NextResponse.json({ok:false,error:"INVALID_PAIR"},{status:400});
 const snapshotAt=new Date().toISOString();stage="build_features";const [viewerSnapshot,candidateSnapshot,forwardPairSnapshot,reversePairSnapshot,forwardReadSignals,reverseReadSignals]=await Promise.all([buildUserFeatures(viewerUserId,snapshotAt),buildUserFeatures(candidateUserId,snapshotAt),buildPairFeatures(viewerUserId,candidateUserId,snapshotAt),buildPairFeatures(candidateUserId,viewerUserId,snapshotAt),buildConversationReadSignalsV1(viewerUserId,candidateUserId,snapshotAt),buildConversationReadSignalsV1(candidateUserId,viewerUserId,snapshotAt)]);
 if([viewerSnapshot,candidateSnapshot,forwardPairSnapshot,reversePairSnapshot].some(s=>s.snapshotAt!==snapshotAt))throw new Error("SNAPSHOT_AT_MISMATCH");
 stage="persist_v1_features";await Promise.all([persistUserFeatureSnapshot(viewerUserId,viewerSnapshot),persistUserFeatureSnapshot(candidateUserId,candidateSnapshot),persistPairFeatureSnapshot(viewerUserId,candidateUserId,forwardPairSnapshot),persistPairFeatureSnapshot(candidateUserId,viewerUserId,reversePairSnapshot)]);
 stage="score_v2";const forwardScore=scoreAuraMatchV2({viewerFeatures:viewerSnapshot.features,candidateFeatures:candidateSnapshot.features,pairFeatures:forwardPairSnapshot.features,featureSchemaVersion:1,snapshotAt}),reverseScore=scoreAuraMatchV2({viewerFeatures:candidateSnapshot.features,candidateFeatures:viewerSnapshot.features,pairFeatures:reversePairSnapshot.features,featureSchemaVersion:1,snapshotAt});
 stage="persist_v2_scores";const [forwardPersisted,reversePersisted]=await Promise.all([persistAuraScore(viewerUserId,candidateUserId,forwardScore),persistAuraScore(candidateUserId,viewerUserId,reverseScore)]);
 const forwardV2:FeatureSnapshotV2<AuraPairFeaturesV2>={featureSchemaVersion:2,snapshotAt,features:{...forwardPairSnapshot.features,...forwardReadSignals}},reverseV2:FeatureSnapshotV2<AuraPairFeaturesV2>={featureSchemaVersion:2,snapshotAt,features:{...reversePairSnapshot.features,...reverseReadSignals}};const viewerV2={featureSchemaVersion:2 as const,snapshotAt,features:viewerSnapshot.features},candidateV2={featureSchemaVersion:2 as const,snapshotAt,features:candidateSnapshot.features};
 stage="score_v3";const forwardShadow=scoreAuraMatchV3({viewerFeatures:viewerSnapshot.features,candidateFeatures:candidateSnapshot.features,pairFeatures:forwardV2.features,snapshotAt}),reverseShadow=scoreAuraMatchV3({viewerFeatures:candidateSnapshot.features,candidateFeatures:viewerSnapshot.features,pairFeatures:reverseV2.features,snapshotAt});
 stage="persist_v2_features_v3_scores";const results=await Promise.all([persistUserFeatureSnapshotV2(viewerUserId,viewerV2),persistUserFeatureSnapshotV2(candidateUserId,candidateV2),persistPairFeatureSnapshotV2(viewerUserId,candidateUserId,forwardV2),persistPairFeatureSnapshotV2(candidateUserId,viewerUserId,reverseV2),persistAuraScore(viewerUserId,candidateUserId,forwardShadow),persistAuraScore(candidateUserId,viewerUserId,reverseShadow)]);const forwardShadowPersisted=results[4],reverseShadowPersisted=results[5];
 stage="audit";try{const {data:admin}=await supabaseAdmin.from("users").select("id").eq("telegram_id",String(authorization.telegramId)).maybeSingle();const audit=await supabaseAdmin.from("aura_admin_audit_log").insert({admin_user_id:admin?.id??null,admin_telegram_id:String(authorization.telegramId),action:"AURA_ADMIN_PAIR_VERIFY",target_type:"user_pair",target_id:`${viewerUserId}:${candidateUserId}`,metadata:{viewer_user_id:viewerUserId,candidate_user_id:candidateUserId,snapshot_at:snapshotAt,forward_score_v2:forwardScore.totalScore,reverse_score_v2:reverseScore.totalScore,forward_shadow_v3:forwardShadow.totalScore,reverse_shadow_v3:reverseShadow.totalScore}});if(audit.error)console.warn("AURA_ADMIN_PAIR_VERIFY_AUDIT_FAILED",{code:audit.error.message});}catch(auditError){console.warn("AURA_ADMIN_PAIR_VERIFY_AUDIT_FAILED",{code:auditError instanceof Error?auditError.message:"UNKNOWN"});}
 return NextResponse.json({ok:true,result:{snapshotAt,pairFeatures:forwardPairSnapshot.features,reversePairFeatures:reversePairSnapshot.features,pairFeaturesV2:forwardV2.features,reversePairFeaturesV2:reverseV2.features,score:forwardPersisted,reverseScore:reversePersisted,shadowScore:forwardShadowPersisted,reverseShadowScore:reverseShadowPersisted}});
 }catch(error){const code=error instanceof Error?error.message:"UNKNOWN";console.error("AURA_ADMIN_PAIR_VERIFY_ERROR",{stage,code});return NextResponse.json({ok:false,error:"PAIR_VERIFY_FAILED",stage,code},{status:500});}}
