import type { ReactNode } from "react";
import AuraSkeleton from "./AuraSkeleton";

function Frame({children,bottomNav=false}:{children:ReactNode;bottomNav?:boolean}){
  return <main aria-busy="true" style={{minHeight:"100dvh",background:"var(--app-bg)",color:"var(--text-primary)",padding:16,paddingBottom:bottomNav?"calc(var(--bottom-nav-height) + env(safe-area-inset-bottom) + 24px)":16}}><div aria-hidden="true" style={{maxWidth:560,margin:"0 auto"}}>{children}</div></main>;
}
export function HeaderSkeleton(){return <div style={{display:"flex",alignItems:"center",gap:12,height:52,marginBottom:16}}><AuraSkeleton width={38} height={38} radius={19}/><div style={{flex:1}}><AuraSkeleton width="45%" height={18}/><div style={{marginTop:7}}><AuraSkeleton width="28%" height={11}/></div></div></div>}
export function ChatListSkeleton(){return <Frame bottomNav><div style={{padding:"6px 2px 12px"}}><AuraSkeleton width={110} height={30}/><div style={{marginTop:18}}><AuraSkeleton height={44} radius={14}/></div></div>{Array.from({length:6},(_,index)=><div key={index} style={{display:"flex",alignItems:"center",gap:12,padding:"12px 2px"}}><AuraSkeleton width={54} height={54} radius={27}/><div style={{flex:1}}><AuraSkeleton width={`${58+(index%3)*8}%`} height={16}/><div style={{marginTop:9}}><AuraSkeleton width={`${72-(index%2)*12}%`} height={12}/></div></div><div style={{display:"grid",justifyItems:"end",gap:9}}><AuraSkeleton width={34} height={10}/>{index<3&&<AuraSkeleton width={22} height={22} radius={11}/>}</div></div>)}</Frame>}
export function ChatScreenSkeleton(){return <Frame><HeaderSkeleton/><div style={{display:"grid",gap:14,paddingTop:20}}>{[48,62,42,70,54].map((width,index)=><div key={index} style={{display:"flex",justifyContent:index%2?"flex-end":"flex-start"}}><AuraSkeleton width={`${width}%`} height={index%2?54:68} radius={20}/></div>)}</div><div style={{position:"fixed",insetInline:16,bottom:"calc(env(safe-area-inset-bottom) + 12px)",display:"flex",gap:10,maxWidth:528,margin:"0 auto"}}><AuraSkeleton height={48} radius={24}/><AuraSkeleton width={48} height={48} radius={24}/></div></Frame>}
export function ListSkeleton({rows=5}:{rows?:number}){return <Frame><HeaderSkeleton/>{Array.from({length:rows},(_,index)=><div key={index} style={{display:"flex",gap:13,alignItems:"center",padding:14,marginBottom:12,background:"var(--surface)",border:"1px solid var(--border-subtle)",borderRadius:18}}><AuraSkeleton width={48} height={48} radius={24}/><div style={{flex:1}}><AuraSkeleton width="58%" height={16}/><div style={{marginTop:9}}><AuraSkeleton width="78%" height={12}/></div></div></div>)}</Frame>}
export function GridSkeleton(){return <Frame bottomNav><HeaderSkeleton/><div style={{display:"grid",gridTemplateColumns:"repeat(2,minmax(0,1fr))",gap:12}}>{Array.from({length:6},(_,index)=><div key={index}><AuraSkeleton height={210} radius={22}/><div style={{marginTop:10}}><AuraSkeleton width="72%" height={16}/></div></div>)}</div></Frame>}
export function FormSkeleton(){return <Frame><HeaderSkeleton/><div style={{display:"grid",gap:16}}><AuraSkeleton height={52} radius={14}/><AuraSkeleton height={110} radius={14}/>{Array.from({length:4},(_,index)=><AuraSkeleton key={index} height={58} radius={16}/>)}</div><div style={{marginTop:24}}><AuraSkeleton height={54} radius={18}/></div></Frame>}
export function AccountSkeleton(){return <Frame bottomNav><div style={{display:"grid",justifyItems:"center",gap:12,paddingTop:12}}><AuraSkeleton width={110} height={110} radius={55}/><AuraSkeleton width={150} height={24}/><AuraSkeleton width={100} height={14}/></div><div style={{display:"grid",gap:12,marginTop:26}}>{Array.from({length:5},(_,index)=><AuraSkeleton key={index} height={54} radius={16}/>)}</div></Frame>}
export function MeetSkeleton({map=false}:{map?:boolean}){return <Frame bottomNav><div style={{display:"flex",gap:10,marginBottom:14}}><AuraSkeleton width={88} height={38} radius={19}/><AuraSkeleton width={88} height={38} radius={19}/></div>{map?<div style={{position:"relative"}}><AuraSkeleton height="calc(100dvh - 160px)" radius={24}/><div style={{position:"absolute",insetInlineEnd:14,top:70,display:"grid",gap:8}}><AuraSkeleton width={44} height={44} radius={14}/><AuraSkeleton width={44} height={44} radius={14}/></div></div>:<div style={{display:"grid",gap:14}}>{Array.from({length:4},(_,index)=><AuraSkeleton key={index} height={220} radius={24}/>)}</div>}</Frame>}
