"use client";

import {useEffect,useState} from "react";
import {getTelegramInitData} from "../../../lib/telegram-init-data";
import type {AuraAdminHealth,AuraAdminOverviewV1} from "../../../lib/server/admin/aura/types";

const WINDOWS=["24h","7d","30d"] as const;
const card:React.CSSProperties={border:"1px solid var(--border)",borderRadius:20,padding:18,background:"var(--surface)",boxShadow:"0 10px 30px rgba(0,0,0,.05)"};
const muted:React.CSSProperties={color:"var(--text-secondary)",fontSize:13};
const grid:React.CSSProperties={display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:14};
const statusColor:Record<AuraAdminHealth,string>={healthy:"#18a06b",stale:"#d58b16",gap:"#d14d5b",empty:"#718096"};
const pct=(value:number)=>`${(value*100).toFixed(1)}%`;

function Status({value}:{value:AuraAdminHealth}){return <span style={{fontSize:11,fontWeight:800,textTransform:"uppercase",padding:"5px 9px",borderRadius:999,color:"white",background:statusColor[value]}}>{value}</span>;}
function Metric({label,value}:{label:string;value:string|number}){return <div><div style={muted}>{label}</div><div style={{fontSize:25,fontWeight:800,marginTop:5}}>{value}</div></div>;}
function date(value:string|null){return value?new Date(value).toLocaleString():"No data";}

export default function AuraAdminPage(){
  const [timeframe,setTimeframe]=useState<(typeof WINDOWS)[number]>("7d");
  const [outcomeWindow,setOutcomeWindow]=useState<(typeof WINDOWS)[number]>("24h");
  const [overview,setOverview]=useState<AuraAdminOverviewV1|null>(null);
  const [state,setState]=useState<"loading"|"ready"|"denied"|"error">("loading");
  useEffect(()=>{let active=true;(async()=>{setState("loading");const initData=await getTelegramInitData();if(!initData){if(active)setState("denied");return;}const response=await fetch("/api/admin/aura/overview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,timeframe,outcomeWindow})});if(!active)return;if(response.status===404){setState("denied");return;}const body=await response.json().catch(()=>null);if(!response.ok||!body?.ok){setState("error");return;}setOverview(body.overview);setState("ready");})().catch(()=>{if(active)setState("error");});return()=>{active=false;};},[timeframe,outcomeWindow]);
  if(state==="denied")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"var(--background)",color:"var(--text-primary)"}}><p>Page not found.</p></main>;
  if(state==="loading")return <main style={{minHeight:"100vh",background:"var(--background)"}}/>;
  if(state==="error")return <main style={{minHeight:"100vh",display:"grid",placeItems:"center",background:"var(--background)",color:"var(--text-primary)"}}><p>Page unavailable.</p></main>;
  return <main style={{minHeight:"100vh",background:"var(--background)",color:"var(--text-primary)",padding:"32px clamp(16px,4vw,56px) 64px"}}>
    <div style={{maxWidth:1180,margin:"0 auto"}}>
      <header style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-end",flexWrap:"wrap",marginBottom:24}}><div><div style={{fontSize:12,fontWeight:800,letterSpacing:1.4,color:"var(--primary)",textTransform:"uppercase"}}>Internal operations</div><h1 style={{fontSize:"clamp(28px,5vw,48px)",margin:"5px 0"}}>AURA Match</h1><p style={{...muted,margin:0}}>Aggregate pipeline health · Observational analysis</p></div><div style={{display:"flex",gap:10,flexWrap:"wrap"}}><label style={muted}>Reporting timeframe<br/><select value={timeframe} onChange={event=>setTimeframe(event.target.value as typeof timeframe)} style={{marginTop:6,padding:"9px 12px",borderRadius:12,border:"1px solid var(--border)",background:"var(--surface)",color:"var(--text-primary)"}}>{WINDOWS.map(value=><option key={value}>{value}</option>)}</select></label><label style={muted}>Outcome horizon<br/><select value={outcomeWindow} onChange={event=>setOutcomeWindow(event.target.value as typeof outcomeWindow)} style={{marginTop:6,padding:"9px 12px",borderRadius:12,border:"1px solid var(--border)",background:"var(--surface)",color:"var(--text-primary)"}}>{WINDOWS.map(value=><option key={value}>{value}</option>)}</select></label></div></header>
      {state==="ready"&&overview&&<>
        <section style={{...grid,marginBottom:14}}>
          <article style={card}><div style={{display:"flex",justifyContent:"space-between"}}><strong>Events</strong><Status value={overview.events.health}/></div><div style={{...grid,marginTop:18}}><Metric label="Last hour" value={overview.events.last1h}/><Metric label="Last 24h" value={overview.events.last24h}/><Metric label="Client / server" value={`${overview.events.clientCount} / ${overview.events.serverCount}`}/></div><p style={muted}>Latest: {date(overview.events.latestReceivedAt)}</p></article>
          <article style={card}><div style={{display:"flex",justifyContent:"space-between"}}><strong>Features</strong><Status value={overview.features.health}/></div><div style={{...grid,marginTop:18}}><Metric label="User · 24h" value={overview.features.userLast24h}/><Metric label="Pair · 24h" value={overview.features.pairLast24h}/></div><p style={muted}>Latest: {date(overview.features.latestSnapshotAt)}</p></article>
          <article style={card}><div style={{display:"flex",justifyContent:"space-between"}}><strong>Scores</strong><Status value={overview.scores.health}/></div><div style={{...grid,marginTop:18}}><Metric label="Last 24h" value={overview.scores.last24h}/><Metric label={`In ${timeframe}`} value={overview.scores.timeframeCount}/></div><p style={muted}>Latest: {date(overview.scores.latestSnapshotAt)}</p></article>
          <article style={card}><div style={{display:"flex",justifyContent:"space-between"}}><strong>Outcomes</strong><Status value={overview.outcomes.health}/></div><div style={{...grid,marginTop:18}}><Metric label={`${outcomeWindow} selected`} value={overview.outcomes.selectedCount}/><Metric label="Null score links" value={overview.outcomes.nullScoreLinks}/></div><p style={muted}>Latest: {date(overview.outcomes.latestEvaluatedAt)}</p></article>
        </section>
        <section style={{...grid,marginBottom:14}}><article style={card}><strong>Ranking mode</strong><div style={{fontSize:30,fontWeight:800,marginTop:12,textTransform:"capitalize"}}>{overview.ranking.mode}</div><p style={muted}>No persisted shadow diagnostics. Mode is read-only.</p></article>{overview.coverage.map(row=><article key={row.windowType} style={card}><div style={{display:"flex",justifyContent:"space-between"}}><strong>{row.windowType} coverage</strong><span style={muted}>{pct(row.coverageRate)}</span></div><div style={{height:8,borderRadius:8,background:"var(--surface-secondary)",margin:"15px 0",overflow:"hidden"}}><div style={{height:"100%",width:`${row.coverageRate*100}%`,background:"var(--primary)"}}/></div><div style={{display:"flex",justifyContent:"space-between",...muted}}><span>{row.materialized} materialized</span><span>{row.missing} missing / {row.eligibleAnchors} eligible</span></div></article>)}</section>
        <section style={{...grid,marginBottom:14}}><article style={card}><strong>Score distribution · {timeframe}</strong><div style={{marginTop:18,display:"grid",gap:12}}>{overview.scores.distribution.map(row=><div key={row.bucket} style={{display:"grid",gridTemplateColumns:"55px 1fr 75px",gap:10,alignItems:"center"}}><span style={muted}>{row.bucket}</span><div style={{height:9,borderRadius:9,background:"var(--surface-secondary)",overflow:"hidden"}}><div style={{height:"100%",width:`${row.percent}%`,background:"linear-gradient(90deg,var(--primary),#9b7cff)"}}/></div><span style={{...muted,textAlign:"right"}}>{row.count} · {row.percent}%</span></div>)}</div></article><article style={card}><strong>Outcome totals</strong><div style={{...grid,marginTop:18}}>{WINDOWS.map(window=><Metric key={window} label={window} value={overview.outcomes.totalByWindow[window]}/>)}</div><p style={muted}>Completed materialized rows only.</p></article></section>
        <section style={card}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><strong>Score → outcome rates</strong><p style={{...muted,margin:"5px 0 16px"}}>Observational · {outcomeWindow} outcomes evaluated in {timeframe}. No causal claim.</p></div></div><div style={{overflowX:"auto"}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:13,minWidth:900}}><thead><tr>{["Score","N","Open","Like","Pass","Match","Chat","Meet","Block","Report"].map(value=><th key={value} style={{textAlign:"right",padding:"10px 8px",borderBottom:"1px solid var(--border)",color:"var(--text-secondary)"}}>{value}</th>)}</tr></thead><tbody>{overview.scoreOutcome.map(row=><tr key={row.bucket}>{[row.bucket,row.count,pct(row.openRate),pct(row.likeRate),pct(row.passRate),pct(row.matchRate),pct(row.chatStartRate),pct(row.meetActivityRate),pct(row.blockRate),pct(row.reportRate)].map((value,index)=><td key={index} style={{textAlign:"right",padding:"11px 8px",borderBottom:"1px solid var(--border)"}}>{value}</td>)}</tr>)}</tbody></table></div></section>
      </>}
    </div>
  </main>;
}
