"use client";

import {useCallback,useEffect,useMemo,useState} from "react";
import {useRouter} from "next/navigation";
import {getTelegramInitData} from "../../../../lib/telegram-init-data";

type User={id:string;name:string;telegram_id?:string|number|null};
type Pair={viewer:User;candidate:User;snapshotAt:string;featureSchemaVersion?:number;features:Record<string,any>;activeScore:any|null;shadowScore:any|null};
type Detail={users:User[];pairSnapshots:{feature_schema_version:number;snapshot_at:string;features:Record<string,any>}[];scores:any[];chat:any|null;messages:{id:string;sender_id:string;body:string|null;created_at:string;message_type:string;is_read?:boolean|null;read_at?:string|null}[];messagesIncluded?:boolean};

const card:React.CSSProperties={border:"1px solid rgba(255,255,255,.08)",borderRadius:20,padding:16,background:"rgba(22,22,28,.94)"};
const muted:React.CSSProperties={color:"#969aa8",fontSize:12,lineHeight:1.45};
const fmt=(v:any)=>v===null||v===undefined?"—":typeof v==="boolean"?(v?"Да":"Нет"):String(v);
const date=(v:string)=>new Date(v).toLocaleString("ru-RU");

export default function AuraConversationDiagnostics(){
  const router=useRouter();
  const [pairs,setPairs]=useState<Pair[]>([]);const [selected,setSelected]=useState<Pair|null>(null);const [detail,setDetail]=useState<Detail|null>(null);const [state,setState]=useState("loading");const [revealing,setRevealing]=useState(false);const [verifying,setVerifying]=useState(false);const [verifyMessage,setVerifyMessage]=useState("");
  const request=useCallback(async(payload:any)=>{const initData=await getTelegramInitData();if(!initData)throw new Error("NO_INIT_DATA");const r=await fetch("/api/admin/aura/conversations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,...payload})});if(r.status===404)throw new Error("DENIED");const b=await r.json();if(!r.ok||!b?.ok)throw new Error(b?.error||"FAILED");return b;},[]);
  const load=useCallback(async()=>{setState("loading");try{const b=await request({mode:"list"});setPairs(b.pairs??[]);setState("ready");}catch{setState("error");}},[request]);
  useEffect(()=>{load();},[load]);
  const openPair=async(pair:Pair)=>{setSelected(pair);setDetail(null);setRevealing(false);setVerifyMessage("");try{const b=await request({mode:"detail",viewerUserId:pair.viewer.id,candidateUserId:pair.candidate.id,includeMessages:false});setDetail(b.detail);}catch{setDetail(null);}};
  const revealMessages=async()=>{if(!selected||revealing)return;setRevealing(true);try{const b=await request({mode:"detail",viewerUserId:selected.viewer.id,candidateUserId:selected.candidate.id,includeMessages:true});setDetail(b.detail);}finally{setRevealing(false);}};
  const verifyPair=async()=>{if(!selected||verifying)return;setVerifying(true);setVerifyMessage("");try{const initData=await getTelegramInitData();if(!initData)throw new Error("NO_INIT_DATA");const response=await fetch("/api/admin/aura/verify-pair",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({initData,viewerUserId:selected.viewer.id,candidateUserId:selected.candidate.id})});const body=await response.json();if(!response.ok||!body?.ok)throw new Error(body?.error||"FAILED");setSelected({...selected,snapshotAt:body.result.snapshotAt,featureSchemaVersion:2,features:body.result.pairFeaturesV2,activeScore:body.result.score,shadowScore:body.result.shadowScore});const refreshed=await request({mode:"detail",viewerUserId:selected.viewer.id,candidateUserId:selected.candidate.id,includeMessages:false});setDetail(refreshed.detail);setVerifyMessage(`Проверено: ACTIVE V2 · ${body.result.score.total_score} | SHADOW V3 · ${body.result.shadowScore.total_score} · обратное направление V2 ${body.result.reverseScore.total_score} / V3 ${body.result.reverseShadowScore.total_score}`);await load();}catch{setVerifyMessage("Проверка не прошла — смотри server log.");}finally{setVerifying(false);}};
  const conversationKeys=useMemo(()=>Object.keys(selected?.features??{}).filter(k=>k.includes("message")||k.includes("reply")||k.includes("read")||k.includes("conversation")||k.includes("chat_days")||k.includes("burst")||k.includes("balance")||k.includes("started_conversation")||k.includes("meet_intent")),[selected]);
  return <main style={{minHeight:"100dvh",background:"#09090c",color:"#f6f7fb",padding:"calc(16px + env(safe-area-inset-top)) 14px 40px"}}><div style={{maxWidth:1100,margin:"0 auto"}}>
    <div style={{display:"flex",justifyContent:"space-between",gap:10,alignItems:"center",marginBottom:16}}><div><div style={{fontSize:11,color:"#8190ff",fontWeight:900,letterSpacing:1.4}}>AURA INTERNAL</div><h1 style={{margin:"3px 0",fontSize:30}}>Диалоги</h1><p style={{...muted,margin:0}}>ACTIVE V2 управляет выдачей. SHADOW V3 считается параллельно и пока только сравнивается.</p></div><button onClick={()=>router.push("/admin/aura")} style={{border:0,borderRadius:12,padding:"10px 12px",fontWeight:800}}>← Назад</button></div>
    {state==="loading"&&<p style={muted}>Загрузка…</p>}{state==="error"&&<div style={card}>Не удалось загрузить диагностику. <button onClick={load}>Повторить</button></div>}
    {state==="ready"&&<div style={{display:"grid",gridTemplateColumns:"minmax(0,1fr)",gap:12}}>{pairs.length===0?<div style={card}>Пока нет pair snapshots.</div>:pairs.map((p,i)=><button key={`${p.viewer.id}:${p.candidate.id}:${i}`} onClick={()=>openPair(p)} style={{...card,textAlign:"left",color:"inherit",cursor:"pointer"}}><div style={{display:"flex",justifyContent:"space-between",gap:8,flexWrap:"wrap"}}><strong>{p.viewer.name||"User"} → {p.candidate.name||"User"}</strong><span style={{fontWeight:900,color:"#9aa5ff"}}>ACTIVE V2 · {p.activeScore?.total_score??"—"} | SHADOW V3 · {p.shadowScore?.total_score??"—"}</span></div><div style={{...muted,marginTop:6}}>Feature schema V{p.featureSchemaVersion??"—"} · {date(p.snapshotAt)} · сообщений: {fmt(p.features.direct_message_count_30d)} · баланс: {fmt(p.features.message_balance_ratio)}</div></button>)}</div>}
    {selected&&<section style={{marginTop:22}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:10,flexWrap:"wrap"}}><h2 style={{margin:0}}>{selected.viewer.name} ↔ {selected.candidate.name}</h2><button onClick={verifyPair} disabled={verifying} style={{border:0,borderRadius:12,padding:"10px 13px",fontWeight:900,background:"#fff",color:"#09090c"}}>{verifying?"Проверяю…":"Пересчитать V2 + Shadow V3"}</button></div>{verifyMessage&&<p style={{...muted,color:verifyMessage.startsWith("Проверено")?"#64d89b":"#f08a96"}}>{verifyMessage}</p>}<p style={muted}>Проверка создаёт V1/V2 feature snapshots, рабочий Score V2 и экспериментальный Score V3 для обоих направлений. V3 не меняет порядок рекомендаций.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:10}}>{conversationKeys.map(k=><div key={k} style={card}><div style={muted}>{k}</div><div style={{fontSize:22,fontWeight:900,marginTop:6}}>{fmt(selected.features[k])}</div></div>)}</div>
      <div style={{...card,marginTop:12}}><strong>Score snapshots</strong>{detail?.scores?.length?<div style={{marginTop:10,display:"grid",gap:8}}>{detail.scores.map((s:any,i:number)=><div key={i} style={{padding:"10px 0",borderBottom:"1px solid rgba(255,255,255,.07)"}}><b>{s.score_version===3?"SHADOW ":""}V{s.score_version} · {s.total_score}</b><div style={muted}>feature V{s.feature_schema_version} · {date(s.snapshot_at)} · reciprocity {fmt(s.components?.reciprocity)} · engagement {fmt(s.components?.engagement)}</div></div>)}</div>:<p style={muted}>Нет score snapshots.</p>}</div>
      <div style={{...card,marginTop:12}}><div style={{display:"flex",justifyContent:"space-between",gap:8,alignItems:"center"}}><strong>Исходные сообщения</strong>{!detail?.messagesIncluded&&<button onClick={revealMessages} disabled={revealing} style={{border:0,borderRadius:10,padding:"9px 12px",fontWeight:800}}>{revealing?"Загрузка…":"Показать"}</button>}</div><p style={muted}>По умолчанию текст скрыт. Явное открытие доступно только администратору и логируется на сервере.</p>{detail?.messagesIncluded&&(detail.messages?.length?<div style={{display:"grid",gap:8,marginTop:10}}>{detail.messages.map(m=>{const u=detail.users.find(x=>x.id===m.sender_id);return <div key={m.id} style={{padding:10,borderRadius:12,background:"rgba(255,255,255,.045)"}}><div style={{fontSize:11,fontWeight:800,color:"#9ba5ff"}}>{u?.name??m.sender_id} · {date(m.created_at)} · {m.is_read?`прочитано${m.read_at?` ${date(m.read_at)}`:""}`:"не прочитано"}</div><div style={{marginTop:5,whiteSpace:"pre-wrap",wordBreak:"break-word"}}>{m.body||`[${m.message_type}]`}</div></div>})}</div>:<p style={muted}>В этом direct-чате сообщений нет.</p>)}</div>
    </section>}
  </div></main>;
}