with checks(check_name,expected,actual,status) as (
  values
    ('reject cooldown definition','15 minutes',pg_get_functiondef('public.dating_reject_cooldown_interval()'::regprocedure),case when pg_get_functiondef('public.dating_reject_cooldown_interval()'::regprocedure) like '%15 minutes%' then 'PASS' else 'FAIL' end),
    ('match cooldown definition','7 days',pg_get_functiondef('public.dating_match_cooldown_interval()'::regprocedure),case when pg_get_functiondef('public.dating_match_cooldown_interval()'::regprocedure) like '%7 days%' then 'PASS' else 'FAIL' end),
    ('pending cycles without cooldown','0',(select count(*)::text from public.dating_interaction_cycles where status='pending' and (completed_at is not null or cooldown_until is not null)),case when not exists(select 1 from public.dating_interaction_cycles where status='pending' and (completed_at is not null or cooldown_until is not null)) then 'PASS' else 'FAIL' end),
    ('rejected cooldown upper bound','0',(select count(*)::text from public.dating_interaction_cycles where status='rejected' and cooldown_until>completed_at+interval '15 minutes'),case when not exists(select 1 from public.dating_interaction_cycles where status='rejected' and cooldown_until>completed_at+interval '15 minutes') then 'PASS' else 'FAIL' end),
    ('matched cooldown upper bound','0',(select count(*)::text from public.dating_interaction_cycles where status='matched' and cooldown_until>completed_at+interval '7 days'),case when not exists(select 1 from public.dating_interaction_cycles where status='matched' and cooldown_until>completed_at+interval '7 days') then 'PASS' else 'FAIL' end),
    ('feed has directional pending','recipient_user_id=p_user_id',pg_get_functiondef('public.get_dating_feed(uuid,integer,uuid[])'::regprocedure),case when pg_get_functiondef('public.get_dating_feed(uuid,integer,uuid[])'::regprocedure) like '%recipient_user_id=p_user_id%' then 'PASS' else 'FAIL' end),
    ('feed has no chat exclusion','no public.chats reference',pg_get_functiondef('public.get_dating_feed(uuid,integer,uuid[])'::regprocedure),case when pg_get_functiondef('public.get_dating_feed(uuid,integer,uuid[])'::regprocedure) not like '%public.chats%' then 'PASS' else 'FAIL' end),
    ('browser RPC execute','0',(select count(*)::text from information_schema.routine_privileges where specific_schema='public' and routine_name in ('process_dating_action','get_dating_feed','dating_reject_cooldown_interval','dating_match_cooldown_interval') and grantee in ('PUBLIC','anon','authenticated') and privilege_type='EXECUTE'),case when not exists(select 1 from information_schema.routine_privileges where specific_schema='public' and routine_name in ('process_dating_action','get_dating_feed','dating_reject_cooldown_interval','dating_match_cooldown_interval') and grantee in ('PUBLIC','anon','authenticated') and privilege_type='EXECUTE') then 'PASS' else 'FAIL' end),
    ('service RPC execute','4',(select count(distinct routine_name)::text from information_schema.routine_privileges where specific_schema='public' and routine_name in ('process_dating_action','get_dating_feed','dating_reject_cooldown_interval','dating_match_cooldown_interval') and grantee='service_role' and privilege_type='EXECUTE'),case when (select count(distinct routine_name) from information_schema.routine_privileges where specific_schema='public' and routine_name in ('process_dating_action','get_dating_feed','dating_reject_cooldown_interval','dating_match_cooldown_interval') and grantee='service_role' and privilege_type='EXECUTE')=4 then 'PASS' else 'FAIL' end)
)
select * from checks order by check_name;
